---
- name: Deploy the latest Flask app
  hosts: localhost
  tasks:
    - name: Stop the running container
      docker_container:
        name: flask
        state: stopped
        image: mensahme01/flask

    - name: Remove the stopped container
      docker_container:
        name: flask
        state: absent

    - name: Pull the latest image from Docker Hub
      docker_image:
        name: mensahme01/flask
        tag: latest
        source: pull

    - name: Run the container with the latest image
      docker_container:
        name: flask
        image: mensahme01/flask:latest
        state: started
        detach: yes
        tty: yes
        ports:
          - "8001:7000"
        restart_policy: always